/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * View модель фильтра \&quot;Список карт\&quot;.
 */
@ApiModel(description = "View модель фильтра \"Список карт\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class CardListFilterViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isDeletedFilterType")
  private Boolean isDeletedFilterType = null;

  @JsonProperty("cardsNumbers")
  private List<String> cardsNumbers = null;

  @JsonProperty("ignoreDeletedCards")
  private Boolean ignoreDeletedCards = null;

  public CardListFilterViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CardListFilterViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CardListFilterViewModel isDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
    return this;
  }

   /**
   * Get isDeletedFilterType
   * @return isDeletedFilterType
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeletedFilterType() {
    return isDeletedFilterType;
  }

  public void setIsDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
  }

  public CardListFilterViewModel cardsNumbers(List<String> cardsNumbers) {
    this.cardsNumbers = cardsNumbers;
    return this;
  }

  public CardListFilterViewModel addCardsNumbersItem(String cardsNumbersItem) {
    if (this.cardsNumbers == null) {
      this.cardsNumbers = new ArrayList<>();
    }
    this.cardsNumbers.add(cardsNumbersItem);
    return this;
  }

   /**
   * Список номеров выбранных карт.
   * @return cardsNumbers
  **/
  @ApiModelProperty(value = "Список номеров выбранных карт.")
  public List<String> getCardsNumbers() {
    return cardsNumbers;
  }

  public void setCardsNumbers(List<String> cardsNumbers) {
    this.cardsNumbers = cardsNumbers;
  }

  public CardListFilterViewModel ignoreDeletedCards(Boolean ignoreDeletedCards) {
    this.ignoreDeletedCards = ignoreDeletedCards;
    return this;
  }

   /**
   * Игнорировать удаленные карты.
   * @return ignoreDeletedCards
  **/
  @ApiModelProperty(value = "Игнорировать удаленные карты.")
  public Boolean isIgnoreDeletedCards() {
    return ignoreDeletedCards;
  }

  public void setIgnoreDeletedCards(Boolean ignoreDeletedCards) {
    this.ignoreDeletedCards = ignoreDeletedCards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardListFilterViewModel cardListFilterViewModel = (CardListFilterViewModel) o;
    return Objects.equals(this.id, cardListFilterViewModel.id) &&
        Objects.equals(this.name, cardListFilterViewModel.name) &&
        Objects.equals(this.isDeletedFilterType, cardListFilterViewModel.isDeletedFilterType) &&
        Objects.equals(this.cardsNumbers, cardListFilterViewModel.cardsNumbers) &&
        Objects.equals(this.ignoreDeletedCards, cardListFilterViewModel.ignoreDeletedCards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isDeletedFilterType, cardsNumbers, ignoreDeletedCards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardListFilterViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isDeletedFilterType: ").append(toIndentedString(isDeletedFilterType)).append("\n");
    sb.append("    cardsNumbers: ").append(toIndentedString(cardsNumbers)).append("\n");
    sb.append("    ignoreDeletedCards: ").append(toIndentedString(ignoreDeletedCards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

