/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Дополнительная информация для фасовки карты.
 */
@ApiModel(description = "Дополнительная информация для фасовки карты.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class CardPackingModel {
  @JsonProperty("secondaryCardsIds")
  private List<Integer> secondaryCardsIds = null;

  public CardPackingModel secondaryCardsIds(List<Integer> secondaryCardsIds) {
    this.secondaryCardsIds = secondaryCardsIds;
    return this;
  }

  public CardPackingModel addSecondaryCardsIdsItem(Integer secondaryCardsIdsItem) {
    if (this.secondaryCardsIds == null) {
      this.secondaryCardsIds = new ArrayList<>();
    }
    this.secondaryCardsIds.add(secondaryCardsIdsItem);
    return this;
  }

   /**
   * Идентификаторы фасуемых дополнительных карт.
   * @return secondaryCardsIds
  **/
  @ApiModelProperty(value = "Идентификаторы фасуемых дополнительных карт.")
  public List<Integer> getSecondaryCardsIds() {
    return secondaryCardsIds;
  }

  public void setSecondaryCardsIds(List<Integer> secondaryCardsIds) {
    this.secondaryCardsIds = secondaryCardsIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardPackingModel cardPackingModel = (CardPackingModel) o;
    return Objects.equals(this.secondaryCardsIds, cardPackingModel.secondaryCardsIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secondaryCardsIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardPackingModel {\n");
    
    sb.append("    secondaryCardsIds: ").append(toIndentedString(secondaryCardsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

