/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ViewModel для фильтра \&quot;Наличие товара в чеке\&quot;.
 */
@ApiModel(description = "ViewModel для фильтра \"Наличие товара в чеке\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class ChequeGoodsFilterViewModel {
  /**
   * Тип фильтрации.
   */
  public enum TypeEnum {
    ONLYGOODS("OnlyGoods"),
    
    GOODSQUANTITY("GoodsQuantity"),
    
    GOODSAMOUNT("GoodsAmount");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  /**
   * Операция для фильтра.
   */
  public enum OperationEnum {
    MORE("More"),
    
    LESS("Less"),
    
    EQUALS("Equals"),
    
    BETWEEN("Between"),
    
    MOREOREQUAL("MoreOrEqual"),
    
    LESSOREQUAL("LessOrEqual"),
    
    BETWEENLESSEQUAL("BetweenLessEqual"),
    
    BETWEENMOREEQUAL("BetweenMoreEqual"),
    
    BETWEENEQUAL("BetweenEqual"),
    
    EACH("Each");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation = null;

  @JsonProperty("firstValue")
  private Double firstValue = null;

  @JsonProperty("secondValue")
  private Double secondValue = null;

  @JsonProperty("goodsGroups")
  private List<GoodsGroupViewModel> goodsGroups = null;

  @JsonProperty("personalOfferAttributeId")
  private Integer personalOfferAttributeId = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isDeletedFilterType")
  private Boolean isDeletedFilterType = null;

  public ChequeGoodsFilterViewModel type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Тип фильтрации.
   * @return type
  **/
  @ApiModelProperty(value = "Тип фильтрации.")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ChequeGoodsFilterViewModel operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Операция для фильтра.
   * @return operation
  **/
  @ApiModelProperty(value = "Операция для фильтра.")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public ChequeGoodsFilterViewModel firstValue(Double firstValue) {
    this.firstValue = firstValue;
    return this;
  }

   /**
   * Первое значение для операции.
   * @return firstValue
  **/
  @ApiModelProperty(value = "Первое значение для операции.")
  public Double getFirstValue() {
    return firstValue;
  }

  public void setFirstValue(Double firstValue) {
    this.firstValue = firstValue;
  }

  public ChequeGoodsFilterViewModel secondValue(Double secondValue) {
    this.secondValue = secondValue;
    return this;
  }

   /**
   * Второе значение для операции.
   * @return secondValue
  **/
  @ApiModelProperty(value = "Второе значение для операции.")
  public Double getSecondValue() {
    return secondValue;
  }

  public void setSecondValue(Double secondValue) {
    this.secondValue = secondValue;
  }

  public ChequeGoodsFilterViewModel goodsGroups(List<GoodsGroupViewModel> goodsGroups) {
    this.goodsGroups = goodsGroups;
    return this;
  }

  public ChequeGoodsFilterViewModel addGoodsGroupsItem(GoodsGroupViewModel goodsGroupsItem) {
    if (this.goodsGroups == null) {
      this.goodsGroups = new ArrayList<>();
    }
    this.goodsGroups.add(goodsGroupsItem);
    return this;
  }

   /**
   * Список выбранных групп товаров.
   * @return goodsGroups
  **/
  @ApiModelProperty(value = "Список выбранных групп товаров.")
  public List<GoodsGroupViewModel> getGoodsGroups() {
    return goodsGroups;
  }

  public void setGoodsGroups(List<GoodsGroupViewModel> goodsGroups) {
    this.goodsGroups = goodsGroups;
  }

  public ChequeGoodsFilterViewModel personalOfferAttributeId(Integer personalOfferAttributeId) {
    this.personalOfferAttributeId = personalOfferAttributeId;
    return this;
  }

   /**
   * Идентификатор атрибута \&quot;Персональное предложение\&quot;.
   * @return personalOfferAttributeId
  **/
  @ApiModelProperty(value = "Идентификатор атрибута \"Персональное предложение\".")
  public Integer getPersonalOfferAttributeId() {
    return personalOfferAttributeId;
  }

  public void setPersonalOfferAttributeId(Integer personalOfferAttributeId) {
    this.personalOfferAttributeId = personalOfferAttributeId;
  }

  public ChequeGoodsFilterViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ChequeGoodsFilterViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ChequeGoodsFilterViewModel isDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
    return this;
  }

   /**
   * Get isDeletedFilterType
   * @return isDeletedFilterType
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeletedFilterType() {
    return isDeletedFilterType;
  }

  public void setIsDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChequeGoodsFilterViewModel chequeGoodsFilterViewModel = (ChequeGoodsFilterViewModel) o;
    return Objects.equals(this.type, chequeGoodsFilterViewModel.type) &&
        Objects.equals(this.operation, chequeGoodsFilterViewModel.operation) &&
        Objects.equals(this.firstValue, chequeGoodsFilterViewModel.firstValue) &&
        Objects.equals(this.secondValue, chequeGoodsFilterViewModel.secondValue) &&
        Objects.equals(this.goodsGroups, chequeGoodsFilterViewModel.goodsGroups) &&
        Objects.equals(this.personalOfferAttributeId, chequeGoodsFilterViewModel.personalOfferAttributeId) &&
        Objects.equals(this.id, chequeGoodsFilterViewModel.id) &&
        Objects.equals(this.name, chequeGoodsFilterViewModel.name) &&
        Objects.equals(this.isDeletedFilterType, chequeGoodsFilterViewModel.isDeletedFilterType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, operation, firstValue, secondValue, goodsGroups, personalOfferAttributeId, id, name, isDeletedFilterType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChequeGoodsFilterViewModel {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    firstValue: ").append(toIndentedString(firstValue)).append("\n");
    sb.append("    secondValue: ").append(toIndentedString(secondValue)).append("\n");
    sb.append("    goodsGroups: ").append(toIndentedString(goodsGroups)).append("\n");
    sb.append("    personalOfferAttributeId: ").append(toIndentedString(personalOfferAttributeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isDeletedFilterType: ").append(toIndentedString(isDeletedFilterType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

