/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Фильтр для поиска категорий рекламных материалов.
 */
@ApiModel(description = "Фильтр для поиска категорий рекламных материалов.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class CommunicationOfferCategoryFilter {
  @JsonProperty("name")
  private String name = null;

  /**
   * Признак архивирования категории.
   */
  public enum StateEnum {
    ARCHIVED("Archived"),
    
    NONARCHIVED("NonArchived");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("partnersIds")
  private List<Integer> partnersIds = null;

  @JsonProperty("sortingIds")
  private List<Integer> sortingIds = null;

  public CommunicationOfferCategoryFilter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Название категории.
   * @return name
  **/
  @ApiModelProperty(value = "Название категории.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CommunicationOfferCategoryFilter state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Признак архивирования категории.
   * @return state
  **/
  @ApiModelProperty(value = "Признак архивирования категории.")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public CommunicationOfferCategoryFilter partnersIds(List<Integer> partnersIds) {
    this.partnersIds = partnersIds;
    return this;
  }

  public CommunicationOfferCategoryFilter addPartnersIdsItem(Integer partnersIdsItem) {
    if (this.partnersIds == null) {
      this.partnersIds = new ArrayList<>();
    }
    this.partnersIds.add(partnersIdsItem);
    return this;
  }

   /**
   * Список идентификаторов партнеров.
   * @return partnersIds
  **/
  @ApiModelProperty(value = "Список идентификаторов партнеров.")
  public List<Integer> getPartnersIds() {
    return partnersIds;
  }

  public void setPartnersIds(List<Integer> partnersIds) {
    this.partnersIds = partnersIds;
  }

  public CommunicationOfferCategoryFilter sortingIds(List<Integer> sortingIds) {
    this.sortingIds = sortingIds;
    return this;
  }

  public CommunicationOfferCategoryFilter addSortingIdsItem(Integer sortingIdsItem) {
    if (this.sortingIds == null) {
      this.sortingIds = new ArrayList<>();
    }
    this.sortingIds.add(sortingIdsItem);
    return this;
  }

   /**
   * Идентификаторы, которые будут выбираться первыми.
   * @return sortingIds
  **/
  @ApiModelProperty(value = "Идентификаторы, которые будут выбираться первыми.")
  public List<Integer> getSortingIds() {
    return sortingIds;
  }

  public void setSortingIds(List<Integer> sortingIds) {
    this.sortingIds = sortingIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationOfferCategoryFilter communicationOfferCategoryFilter = (CommunicationOfferCategoryFilter) o;
    return Objects.equals(this.name, communicationOfferCategoryFilter.name) &&
        Objects.equals(this.state, communicationOfferCategoryFilter.state) &&
        Objects.equals(this.partnersIds, communicationOfferCategoryFilter.partnersIds) &&
        Objects.equals(this.sortingIds, communicationOfferCategoryFilter.sortingIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, state, partnersIds, sortingIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationOfferCategoryFilter {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    partnersIds: ").append(toIndentedString(partnersIds)).append("\n");
    sb.append("    sortingIds: ").append(toIndentedString(sortingIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

