/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Модель кода подтверждения.
 */
@ApiModel(description = "Модель кода подтверждения.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class ConfirmCodeModel {
  @JsonProperty("confirmCode")
  private String confirmCode = null;

  public ConfirmCodeModel confirmCode(String confirmCode) {
    this.confirmCode = confirmCode;
    return this;
  }

   /**
   * Код подтверждения.
   * @return confirmCode
  **/
  @ApiModelProperty(value = "Код подтверждения.")
  public String getConfirmCode() {
    return confirmCode;
  }

  public void setConfirmCode(String confirmCode) {
    this.confirmCode = confirmCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmCodeModel confirmCodeModel = (ConfirmCodeModel) o;
    return Objects.equals(this.confirmCode, confirmCodeModel.confirmCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmCodeModel {\n");
    
    sb.append("    confirmCode: ").append(toIndentedString(confirmCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

