/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Действие акции \&quot;Корректировка оплаты\&quot;.
 */
@ApiModel(description = "Действие акции \"Корректировка оплаты\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class CorrectionPaymentActionDto {
  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("roundValue")
  private Integer roundValue = null;

  public CorrectionPaymentActionDto order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Порядковый номер действия в цепочке.
   * @return order
  **/
  @ApiModelProperty(value = "Порядковый номер действия в цепочке.")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public CorrectionPaymentActionDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id действия в цепочке.
   * @return id
  **/
  @ApiModelProperty(value = "Id действия в цепочке.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CorrectionPaymentActionDto roundValue(Integer roundValue) {
    this.roundValue = roundValue;
    return this;
  }

   /**
   * Значение округления в копейках.
   * @return roundValue
  **/
  @ApiModelProperty(value = "Значение округления в копейках.")
  public Integer getRoundValue() {
    return roundValue;
  }

  public void setRoundValue(Integer roundValue) {
    this.roundValue = roundValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorrectionPaymentActionDto correctionPaymentActionDto = (CorrectionPaymentActionDto) o;
    return Objects.equals(this.order, correctionPaymentActionDto.order) &&
        Objects.equals(this.id, correctionPaymentActionDto.id) &&
        Objects.equals(this.roundValue, correctionPaymentActionDto.roundValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, id, roundValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorrectionPaymentActionDto {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roundValue: ").append(toIndentedString(roundValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

