/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View модель действия \&quot;Корректировка прямой скидки\&quot;.
 */
@ApiModel(description = "View модель действия \"Корректировка прямой скидки\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class CorrectionDiscountActionViewModel {
  @JsonProperty("actionId")
  private Integer actionId = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("roundValue")
  private Integer roundValue = null;

  /**
   * Тип распределения скидки между позициями.
   */
  public enum CorrectionTypeDiscountsEnum {
    ALLCHEQUE("AllCheque"),
    
    WITHOUTDISCOUNT("WithoutDiscount"),
    
    HIGHPRICE("HighPrice");

    private String value;

    CorrectionTypeDiscountsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CorrectionTypeDiscountsEnum fromValue(String text) {
      for (CorrectionTypeDiscountsEnum b : CorrectionTypeDiscountsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("correctionTypeDiscounts")
  private CorrectionTypeDiscountsEnum correctionTypeDiscounts = null;

  public CorrectionDiscountActionViewModel actionId(Integer actionId) {
    this.actionId = actionId;
    return this;
  }

   /**
   * Id действия. Если указан, редактируется действие, иначе создается новое.
   * @return actionId
  **/
  @ApiModelProperty(value = "Id действия. Если указан, редактируется действие, иначе создается новое.")
  public Integer getActionId() {
    return actionId;
  }

  public void setActionId(Integer actionId) {
    this.actionId = actionId;
  }

  public CorrectionDiscountActionViewModel order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Порядок действия.
   * @return order
  **/
  @ApiModelProperty(value = "Порядок действия.")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public CorrectionDiscountActionViewModel roundValue(Integer roundValue) {
    this.roundValue = roundValue;
    return this;
  }

   /**
   * Занчение округления в копейках.
   * @return roundValue
  **/
  @ApiModelProperty(value = "Занчение округления в копейках.")
  public Integer getRoundValue() {
    return roundValue;
  }

  public void setRoundValue(Integer roundValue) {
    this.roundValue = roundValue;
  }

  public CorrectionDiscountActionViewModel correctionTypeDiscounts(CorrectionTypeDiscountsEnum correctionTypeDiscounts) {
    this.correctionTypeDiscounts = correctionTypeDiscounts;
    return this;
  }

   /**
   * Тип распределения скидки между позициями.
   * @return correctionTypeDiscounts
  **/
  @ApiModelProperty(value = "Тип распределения скидки между позициями.")
  public CorrectionTypeDiscountsEnum getCorrectionTypeDiscounts() {
    return correctionTypeDiscounts;
  }

  public void setCorrectionTypeDiscounts(CorrectionTypeDiscountsEnum correctionTypeDiscounts) {
    this.correctionTypeDiscounts = correctionTypeDiscounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorrectionDiscountActionViewModel correctionDiscountActionViewModel = (CorrectionDiscountActionViewModel) o;
    return Objects.equals(this.actionId, correctionDiscountActionViewModel.actionId) &&
        Objects.equals(this.order, correctionDiscountActionViewModel.order) &&
        Objects.equals(this.roundValue, correctionDiscountActionViewModel.roundValue) &&
        Objects.equals(this.correctionTypeDiscounts, correctionDiscountActionViewModel.correctionTypeDiscounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionId, order, roundValue, correctionTypeDiscounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorrectionDiscountActionViewModel {\n");
    
    sb.append("    actionId: ").append(toIndentedString(actionId)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    roundValue: ").append(toIndentedString(roundValue)).append("\n");
    sb.append("    correctionTypeDiscounts: ").append(toIndentedString(correctionTypeDiscounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

