/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Модель редактирования магазинов акции.
 */
@ApiModel(description = "Модель редактирования магазинов акции.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class EditOfferMerchantsModel {
  @JsonProperty("offerId")
  private Integer offerId = null;

  @JsonProperty("merchantIds")
  private List<Integer> merchantIds = null;

  public EditOfferMerchantsModel offerId(Integer offerId) {
    this.offerId = offerId;
    return this;
  }

   /**
   * Id акции.
   * @return offerId
  **/
  @ApiModelProperty(value = "Id акции.")
  public Integer getOfferId() {
    return offerId;
  }

  public void setOfferId(Integer offerId) {
    this.offerId = offerId;
  }

  public EditOfferMerchantsModel merchantIds(List<Integer> merchantIds) {
    this.merchantIds = merchantIds;
    return this;
  }

  public EditOfferMerchantsModel addMerchantIdsItem(Integer merchantIdsItem) {
    if (this.merchantIds == null) {
      this.merchantIds = new ArrayList<>();
    }
    this.merchantIds.add(merchantIdsItem);
    return this;
  }

   /**
   * Список ID магазинов, в которых будет работать акция.
   * @return merchantIds
  **/
  @ApiModelProperty(value = "Список ID магазинов, в которых будет работать акция.")
  public List<Integer> getMerchantIds() {
    return merchantIds;
  }

  public void setMerchantIds(List<Integer> merchantIds) {
    this.merchantIds = merchantIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditOfferMerchantsModel editOfferMerchantsModel = (EditOfferMerchantsModel) o;
    return Objects.equals(this.offerId, editOfferMerchantsModel.offerId) &&
        Objects.equals(this.merchantIds, editOfferMerchantsModel.merchantIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerId, merchantIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditOfferMerchantsModel {\n");
    
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    merchantIds: ").append(toIndentedString(merchantIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

