/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Модель для действия \&quot;Включить оповещение\&quot;.
 */
@ApiModel(description = "Модель для действия \"Включить оповещение\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class EnableTriggeredMailingActionViewModel {
  @JsonProperty("mailingId")
  private Integer mailingId = null;

  @JsonProperty("mailingName")
  private String mailingName = null;

  @JsonProperty("actionId")
  private Integer actionId = null;

  @JsonProperty("order")
  private Integer order = null;

  public EnableTriggeredMailingActionViewModel mailingId(Integer mailingId) {
    this.mailingId = mailingId;
    return this;
  }

   /**
   * Идентификатор рассылки.
   * @return mailingId
  **/
  @ApiModelProperty(value = "Идентификатор рассылки.")
  public Integer getMailingId() {
    return mailingId;
  }

  public void setMailingId(Integer mailingId) {
    this.mailingId = mailingId;
  }

  public EnableTriggeredMailingActionViewModel mailingName(String mailingName) {
    this.mailingName = mailingName;
    return this;
  }

   /**
   * Название рассылки.
   * @return mailingName
  **/
  @ApiModelProperty(value = "Название рассылки.")
  public String getMailingName() {
    return mailingName;
  }

  public void setMailingName(String mailingName) {
    this.mailingName = mailingName;
  }

  public EnableTriggeredMailingActionViewModel actionId(Integer actionId) {
    this.actionId = actionId;
    return this;
  }

   /**
   * Id действия. Если указан, редактируется действие, иначе создается новое.
   * @return actionId
  **/
  @ApiModelProperty(value = "Id действия. Если указан, редактируется действие, иначе создается новое.")
  public Integer getActionId() {
    return actionId;
  }

  public void setActionId(Integer actionId) {
    this.actionId = actionId;
  }

  public EnableTriggeredMailingActionViewModel order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Порядок действия.
   * @return order
  **/
  @ApiModelProperty(value = "Порядок действия.")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnableTriggeredMailingActionViewModel enableTriggeredMailingActionViewModel = (EnableTriggeredMailingActionViewModel) o;
    return Objects.equals(this.mailingId, enableTriggeredMailingActionViewModel.mailingId) &&
        Objects.equals(this.mailingName, enableTriggeredMailingActionViewModel.mailingName) &&
        Objects.equals(this.actionId, enableTriggeredMailingActionViewModel.actionId) &&
        Objects.equals(this.order, enableTriggeredMailingActionViewModel.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mailingId, mailingName, actionId, order);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnableTriggeredMailingActionViewModel {\n");
    
    sb.append("    mailingId: ").append(toIndentedString(mailingId)).append("\n");
    sb.append("    mailingName: ").append(toIndentedString(mailingName)).append("\n");
    sb.append("    actionId: ").append(toIndentedString(actionId)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

