/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Файл.
 */
@ApiModel(description = "Файл.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class FileViewModel {
  @JsonProperty("fileName")
  private String fileName = null;

  @JsonProperty("fileSize")
  private Integer fileSize = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("mimeType")
  private String mimeType = null;

  public FileViewModel fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Имя файла.
   * @return fileName
  **/
  @ApiModelProperty(value = "Имя файла.")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public FileViewModel fileSize(Integer fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Размер файла в байтах.
   * @return fileSize
  **/
  @ApiModelProperty(value = "Размер файла в байтах.")
  public Integer getFileSize() {
    return fileSize;
  }

  public void setFileSize(Integer fileSize) {
    this.fileSize = fileSize;
  }

  public FileViewModel content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Содержимое файла в base64.
   * @return content
  **/
  @ApiModelProperty(value = "Содержимое файла в base64.")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public FileViewModel mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * MIME-тип.
   * @return mimeType
  **/
  @ApiModelProperty(value = "MIME-тип.")
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileViewModel fileViewModel = (FileViewModel) o;
    return Objects.equals(this.fileName, fileViewModel.fileName) &&
        Objects.equals(this.fileSize, fileViewModel.fileSize) &&
        Objects.equals(this.content, fileViewModel.content) &&
        Objects.equals(this.mimeType, fileViewModel.mimeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, fileSize, content, mimeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileViewModel {\n");
    
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

