/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Результат фильтрации.
 */
@ApiModel(description = "Результат фильтрации.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class FilterModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("checkValue")
  private Boolean checkValue = null;

  @JsonProperty("checkDetails")
  private String checkDetails = null;

  public FilterModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор фильтра.
   * @return id
  **/
  @ApiModelProperty(value = "Идентификатор фильтра.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FilterModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Наименование фильтра.
   * @return name
  **/
  @ApiModelProperty(value = "Наименование фильтра.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilterModel checkValue(Boolean checkValue) {
    this.checkValue = checkValue;
    return this;
  }

   /**
   * Значение фильтрации.
   * @return checkValue
  **/
  @ApiModelProperty(value = "Значение фильтрации.")
  public Boolean isCheckValue() {
    return checkValue;
  }

  public void setCheckValue(Boolean checkValue) {
    this.checkValue = checkValue;
  }

  public FilterModel checkDetails(String checkDetails) {
    this.checkDetails = checkDetails;
    return this;
  }

   /**
   * Детали фильтрации.
   * @return checkDetails
  **/
  @ApiModelProperty(value = "Детали фильтрации.")
  public String getCheckDetails() {
    return checkDetails;
  }

  public void setCheckDetails(String checkDetails) {
    this.checkDetails = checkDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterModel filterModel = (FilterModel) o;
    return Objects.equals(this.id, filterModel.id) &&
        Objects.equals(this.name, filterModel.name) &&
        Objects.equals(this.checkValue, filterModel.checkValue) &&
        Objects.equals(this.checkDetails, filterModel.checkDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, checkValue, checkDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    checkValue: ").append(toIndentedString(checkValue)).append("\n");
    sb.append("    checkDetails: ").append(toIndentedString(checkDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

