/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * Ошибка при импорте групп товаров.
 */
@ApiModel(description = "Ошибка при импорте групп товаров.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class GoodsGroupsImportError {
  @JsonProperty("goodsGroupId")
  private UUID goodsGroupId = null;

  @JsonProperty("errorCode")
  private Integer errorCode = null;

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  public GoodsGroupsImportError goodsGroupId(UUID goodsGroupId) {
    this.goodsGroupId = goodsGroupId;
    return this;
  }

   /**
   * Идентификатор группы товаров.
   * @return goodsGroupId
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "Идентификатор группы товаров.")
  public UUID getGoodsGroupId() {
    return goodsGroupId;
  }

  public void setGoodsGroupId(UUID goodsGroupId) {
    this.goodsGroupId = goodsGroupId;
  }

  public GoodsGroupsImportError errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Код ошибки.
   * @return errorCode
  **/
  @ApiModelProperty(value = "Код ошибки.")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public GoodsGroupsImportError errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Описание ошибки.
   * @return errorMessage
  **/
  @ApiModelProperty(value = "Описание ошибки.")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodsGroupsImportError goodsGroupsImportError = (GoodsGroupsImportError) o;
    return Objects.equals(this.goodsGroupId, goodsGroupsImportError.goodsGroupId) &&
        Objects.equals(this.errorCode, goodsGroupsImportError.errorCode) &&
        Objects.equals(this.errorMessage, goodsGroupsImportError.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goodsGroupId, errorCode, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodsGroupsImportError {\n");
    
    sb.append("    goodsGroupId: ").append(toIndentedString(goodsGroupId)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

