/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * Детальная информация, связанная с товаром.
 */
@ApiModel(description = "Детальная информация, связанная с товаром.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class GoodsDetailItem {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("rewardThumbnail")
  private RewardThumbnail rewardThumbnail = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("picture")
  private UUID picture = null;

  @JsonProperty("goodsId")
  private Integer goodsId = null;

  public GoodsDetailItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор детали.
   * @return id
  **/
  @ApiModelProperty(value = "Идентификатор детали.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GoodsDetailItem rewardThumbnail(RewardThumbnail rewardThumbnail) {
    this.rewardThumbnail = rewardThumbnail;
    return this;
  }

   /**
   * Вознаграждение.
   * @return rewardThumbnail
  **/
  @ApiModelProperty(value = "Вознаграждение.")
  public RewardThumbnail getRewardThumbnail() {
    return rewardThumbnail;
  }

  public void setRewardThumbnail(RewardThumbnail rewardThumbnail) {
    this.rewardThumbnail = rewardThumbnail;
  }

  public GoodsDetailItem title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Заголовок.
   * @return title
  **/
  @ApiModelProperty(value = "Заголовок.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public GoodsDetailItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Описание.
   * @return description
  **/
  @ApiModelProperty(value = "Описание.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public GoodsDetailItem picture(UUID picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Изображение.
   * @return picture
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "Изображение.")
  public UUID getPicture() {
    return picture;
  }

  public void setPicture(UUID picture) {
    this.picture = picture;
  }

  public GoodsDetailItem goodsId(Integer goodsId) {
    this.goodsId = goodsId;
    return this;
  }

   /**
   * Идентификатор товара.
   * @return goodsId
  **/
  @ApiModelProperty(value = "Идентификатор товара.")
  public Integer getGoodsId() {
    return goodsId;
  }

  public void setGoodsId(Integer goodsId) {
    this.goodsId = goodsId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodsDetailItem goodsDetailItem = (GoodsDetailItem) o;
    return Objects.equals(this.id, goodsDetailItem.id) &&
        Objects.equals(this.rewardThumbnail, goodsDetailItem.rewardThumbnail) &&
        Objects.equals(this.title, goodsDetailItem.title) &&
        Objects.equals(this.description, goodsDetailItem.description) &&
        Objects.equals(this.picture, goodsDetailItem.picture) &&
        Objects.equals(this.goodsId, goodsDetailItem.goodsId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rewardThumbnail, title, description, picture, goodsId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodsDetailItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rewardThumbnail: ").append(toIndentedString(rewardThumbnail)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    goodsId: ").append(toIndentedString(goodsId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

