/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Модель нового изображения с файлом.
 */
@ApiModel(description = "Модель нового изображения с файлом.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class NewImageFileModel {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("file")
  private NewFileModel file = null;

  public NewImageFileModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Описание.
   * @return description
  **/
  @ApiModelProperty(value = "Описание.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public NewImageFileModel file(NewFileModel file) {
    this.file = file;
    return this;
  }

   /**
   * Новый файл.
   * @return file
  **/
  @ApiModelProperty(value = "Новый файл.")
  public NewFileModel getFile() {
    return file;
  }

  public void setFile(NewFileModel file) {
    this.file = file;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewImageFileModel newImageFileModel = (NewImageFileModel) o;
    return Objects.equals(this.description, newImageFileModel.description) &&
        Objects.equals(this.file, newImageFileModel.file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, file);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewImageFileModel {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

