/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * OfferVersionChangeModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class OfferVersionChangeModel {
  @JsonProperty("elementName")
  private String elementName = null;

  @JsonProperty("changesDate")
  private OffsetDateTime changesDate = null;

  /**
   * Gets or Sets changeType
   */
  public enum ChangeTypeEnum {
    ITEMADDED("ItemAdded"),
    
    ITEMREMOVED("ItemRemoved"),
    
    ITEMCHANGED("ItemChanged");

    private String value;

    ChangeTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChangeTypeEnum fromValue(String text) {
      for (ChangeTypeEnum b : ChangeTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("changeType")
  private ChangeTypeEnum changeType = null;

  @JsonProperty("changesAuthor")
  private String changesAuthor = null;

  @JsonProperty("changes")
  private List<String> changes = null;

  public OfferVersionChangeModel elementName(String elementName) {
    this.elementName = elementName;
    return this;
  }

   /**
   * Get elementName
   * @return elementName
  **/
  @ApiModelProperty(value = "")
  public String getElementName() {
    return elementName;
  }

  public void setElementName(String elementName) {
    this.elementName = elementName;
  }

  public OfferVersionChangeModel changesDate(OffsetDateTime changesDate) {
    this.changesDate = changesDate;
    return this;
  }

   /**
   * Get changesDate
   * @return changesDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getChangesDate() {
    return changesDate;
  }

  public void setChangesDate(OffsetDateTime changesDate) {
    this.changesDate = changesDate;
  }

  public OfferVersionChangeModel changeType(ChangeTypeEnum changeType) {
    this.changeType = changeType;
    return this;
  }

   /**
   * Get changeType
   * @return changeType
  **/
  @ApiModelProperty(value = "")
  public ChangeTypeEnum getChangeType() {
    return changeType;
  }

  public void setChangeType(ChangeTypeEnum changeType) {
    this.changeType = changeType;
  }

  public OfferVersionChangeModel changesAuthor(String changesAuthor) {
    this.changesAuthor = changesAuthor;
    return this;
  }

   /**
   * Get changesAuthor
   * @return changesAuthor
  **/
  @ApiModelProperty(value = "")
  public String getChangesAuthor() {
    return changesAuthor;
  }

  public void setChangesAuthor(String changesAuthor) {
    this.changesAuthor = changesAuthor;
  }

  public OfferVersionChangeModel changes(List<String> changes) {
    this.changes = changes;
    return this;
  }

  public OfferVersionChangeModel addChangesItem(String changesItem) {
    if (this.changes == null) {
      this.changes = new ArrayList<>();
    }
    this.changes.add(changesItem);
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(value = "")
  public List<String> getChanges() {
    return changes;
  }

  public void setChanges(List<String> changes) {
    this.changes = changes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferVersionChangeModel offerVersionChangeModel = (OfferVersionChangeModel) o;
    return Objects.equals(this.elementName, offerVersionChangeModel.elementName) &&
        Objects.equals(this.changesDate, offerVersionChangeModel.changesDate) &&
        Objects.equals(this.changeType, offerVersionChangeModel.changeType) &&
        Objects.equals(this.changesAuthor, offerVersionChangeModel.changesAuthor) &&
        Objects.equals(this.changes, offerVersionChangeModel.changes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elementName, changesDate, changeType, changesAuthor, changes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferVersionChangeModel {\n");
    
    sb.append("    elementName: ").append(toIndentedString(elementName)).append("\n");
    sb.append("    changesDate: ").append(toIndentedString(changesDate)).append("\n");
    sb.append("    changeType: ").append(toIndentedString(changeType)).append("\n");
    sb.append("    changesAuthor: ").append(toIndentedString(changesAuthor)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

