/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View-модель переменной контекста.
 */
@ApiModel(description = "View-модель переменной контекста.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class OfferEventContextVariableViewModel {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("displayName")
  private String displayName = null;

  public OfferEventContextVariableViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Имя переменной.
   * @return name
  **/
  @ApiModelProperty(value = "Имя переменной.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OfferEventContextVariableViewModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Отображаемое имя переменной.
   * @return displayName
  **/
  @ApiModelProperty(value = "Отображаемое имя переменной.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferEventContextVariableViewModel offerEventContextVariableViewModel = (OfferEventContextVariableViewModel) o;
    return Objects.equals(this.name, offerEventContextVariableViewModel.name) &&
        Objects.equals(this.displayName, offerEventContextVariableViewModel.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferEventContextVariableViewModel {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

