/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Модель представления для операции. (Дублирует класс).
 */
@ApiModel(description = "Модель представления для операции. (Дублирует класс).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class OperationDataModel {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("amount")
  private Double amount = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("externalInfo")
  private String externalInfo = null;

  public OperationDataModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Описание операции.
   * @return description
  **/
  @ApiModelProperty(value = "Описание операции.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OperationDataModel amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Сумма.
   * @return amount
  **/
  @ApiModelProperty(value = "Сумма.")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public OperationDataModel cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Номер карты.
   * @return cardNumber
  **/
  @ApiModelProperty(value = "Номер карты.")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public OperationDataModel externalInfo(String externalInfo) {
    this.externalInfo = externalInfo;
    return this;
  }

   /**
   * Внешняя информация об операции.
   * @return externalInfo
  **/
  @ApiModelProperty(value = "Внешняя информация об операции.")
  public String getExternalInfo() {
    return externalInfo;
  }

  public void setExternalInfo(String externalInfo) {
    this.externalInfo = externalInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationDataModel operationDataModel = (OperationDataModel) o;
    return Objects.equals(this.description, operationDataModel.description) &&
        Objects.equals(this.amount, operationDataModel.amount) &&
        Objects.equals(this.cardNumber, operationDataModel.cardNumber) &&
        Objects.equals(this.externalInfo, operationDataModel.externalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, amount, cardNumber, externalInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationDataModel {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    externalInfo: ").append(toIndentedString(externalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

