/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Фильтр пользователей.
 */
@ApiModel(description = "Фильтр пользователей.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class PersonFilter {
  @JsonProperty("identifierText")
  private String identifierText = null;

  /**
   * Gets or Sets personInfoStates
   */
  public enum PersonInfoStatesEnum {
    NORMAL("Normal"),
    
    REGISTERED("Registered"),
    
    ANONYMOUS("Anonymous"),
    
    DELETED("Deleted"),
    
    DEREGISTERED("Deregistered");

    private String value;

    PersonInfoStatesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PersonInfoStatesEnum fromValue(String text) {
      for (PersonInfoStatesEnum b : PersonInfoStatesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("personInfoStates")
  private List<PersonInfoStatesEnum> personInfoStates = null;

  @JsonProperty("attribute")
  private SearchUserAttributeValueModel attribute = null;

  public PersonFilter identifierText(String identifierText) {
    this.identifierText = identifierText;
    return this;
  }

   /**
   * Только пользователи с идентификаторами содержащими данный текст.
   * @return identifierText
  **/
  @ApiModelProperty(value = "Только пользователи с идентификаторами содержащими данный текст.")
  public String getIdentifierText() {
    return identifierText;
  }

  public void setIdentifierText(String identifierText) {
    this.identifierText = identifierText;
  }

  public PersonFilter personInfoStates(List<PersonInfoStatesEnum> personInfoStates) {
    this.personInfoStates = personInfoStates;
    return this;
  }

  public PersonFilter addPersonInfoStatesItem(PersonInfoStatesEnum personInfoStatesItem) {
    if (this.personInfoStates == null) {
      this.personInfoStates = new ArrayList<>();
    }
    this.personInfoStates.add(personInfoStatesItem);
    return this;
  }

   /**
   * Список состояний пользователя.
   * @return personInfoStates
  **/
  @ApiModelProperty(value = "Список состояний пользователя.")
  public List<PersonInfoStatesEnum> getPersonInfoStates() {
    return personInfoStates;
  }

  public void setPersonInfoStates(List<PersonInfoStatesEnum> personInfoStates) {
    this.personInfoStates = personInfoStates;
  }

  public PersonFilter attribute(SearchUserAttributeValueModel attribute) {
    this.attribute = attribute;
    return this;
  }

   /**
   * Атрибут и его значение.
   * @return attribute
  **/
  @ApiModelProperty(value = "Атрибут и его значение.")
  public SearchUserAttributeValueModel getAttribute() {
    return attribute;
  }

  public void setAttribute(SearchUserAttributeValueModel attribute) {
    this.attribute = attribute;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonFilter personFilter = (PersonFilter) o;
    return Objects.equals(this.identifierText, personFilter.identifierText) &&
        Objects.equals(this.personInfoStates, personFilter.personInfoStates) &&
        Objects.equals(this.attribute, personFilter.attribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifierText, personInfoStates, attribute);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonFilter {\n");
    
    sb.append("    identifierText: ").append(toIndentedString(identifierText)).append("\n");
    sb.append("    personInfoStates: ").append(toIndentedString(personInfoStates)).append("\n");
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

