/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Модель роли для идентификатора.
 */
@ApiModel(description = "Модель роли для идентификатора.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class PersonIdentifierRoleModel {
  @JsonProperty("role")
  private RoleModel role = null;

  @JsonProperty("partnerIds")
  private List<Integer> partnerIds = null;

  public PersonIdentifierRoleModel role(RoleModel role) {
    this.role = role;
    return this;
  }

   /**
   * Роль.
   * @return role
  **/
  @ApiModelProperty(value = "Роль.")
  public RoleModel getRole() {
    return role;
  }

  public void setRole(RoleModel role) {
    this.role = role;
  }

  public PersonIdentifierRoleModel partnerIds(List<Integer> partnerIds) {
    this.partnerIds = partnerIds;
    return this;
  }

  public PersonIdentifierRoleModel addPartnerIdsItem(Integer partnerIdsItem) {
    if (this.partnerIds == null) {
      this.partnerIds = new ArrayList<>();
    }
    this.partnerIds.add(partnerIdsItem);
    return this;
  }

   /**
   * Партнеры.
   * @return partnerIds
  **/
  @ApiModelProperty(value = "Партнеры.")
  public List<Integer> getPartnerIds() {
    return partnerIds;
  }

  public void setPartnerIds(List<Integer> partnerIds) {
    this.partnerIds = partnerIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonIdentifierRoleModel personIdentifierRoleModel = (PersonIdentifierRoleModel) o;
    return Objects.equals(this.role, personIdentifierRoleModel.role) &&
        Objects.equals(this.partnerIds, personIdentifierRoleModel.partnerIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, partnerIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonIdentifierRoleModel {\n");
    
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    partnerIds: ").append(toIndentedString(partnerIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

