/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View модель фильтра \&quot;Привязан телефон\&quot;.
 */
@ApiModel(description = "View модель фильтра \"Привязан телефон\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class PhoneBindingFilterViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isDeletedFilterType")
  private Boolean isDeletedFilterType = null;

  @JsonProperty("phoneBinded")
  private Boolean phoneBinded = null;

  public PhoneBindingFilterViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public PhoneBindingFilterViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PhoneBindingFilterViewModel isDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
    return this;
  }

   /**
   * Get isDeletedFilterType
   * @return isDeletedFilterType
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeletedFilterType() {
    return isDeletedFilterType;
  }

  public void setIsDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
  }

  public PhoneBindingFilterViewModel phoneBinded(Boolean phoneBinded) {
    this.phoneBinded = phoneBinded;
    return this;
  }

   /**
   * Привязан телефон или нет.
   * @return phoneBinded
  **/
  @ApiModelProperty(value = "Привязан телефон или нет.")
  public Boolean isPhoneBinded() {
    return phoneBinded;
  }

  public void setPhoneBinded(Boolean phoneBinded) {
    this.phoneBinded = phoneBinded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneBindingFilterViewModel phoneBindingFilterViewModel = (PhoneBindingFilterViewModel) o;
    return Objects.equals(this.id, phoneBindingFilterViewModel.id) &&
        Objects.equals(this.name, phoneBindingFilterViewModel.name) &&
        Objects.equals(this.isDeletedFilterType, phoneBindingFilterViewModel.isDeletedFilterType) &&
        Objects.equals(this.phoneBinded, phoneBindingFilterViewModel.phoneBinded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isDeletedFilterType, phoneBinded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneBindingFilterViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isDeletedFilterType: ").append(toIndentedString(isDeletedFilterType)).append("\n");
    sb.append("    phoneBinded: ").append(toIndentedString(phoneBinded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

