/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Фильтр \&quot;Привязка телефона\&quot;.
 */
@ApiModel(description = "Фильтр \"Привязка телефона\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class PhoneBindingFilterDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("phoneBinded")
  private Boolean phoneBinded = null;

  public PhoneBindingFilterDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Имя фильтра.
   * @return name
  **/
  @ApiModelProperty(value = "Имя фильтра.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PhoneBindingFilterDto phoneBinded(Boolean phoneBinded) {
    this.phoneBinded = phoneBinded;
    return this;
  }

   /**
   * Привязан телефон или нет.
   * @return phoneBinded
  **/
  @ApiModelProperty(value = "Привязан телефон или нет.")
  public Boolean isPhoneBinded() {
    return phoneBinded;
  }

  public void setPhoneBinded(Boolean phoneBinded) {
    this.phoneBinded = phoneBinded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneBindingFilterDto phoneBindingFilterDto = (PhoneBindingFilterDto) o;
    return Objects.equals(this.name, phoneBindingFilterDto.name) &&
        Objects.equals(this.phoneBinded, phoneBindingFilterDto.phoneBinded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, phoneBinded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneBindingFilterDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phoneBinded: ").append(toIndentedString(phoneBinded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

