/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Фильтр \&quot;Наличие реферера\&quot;.
 */
@ApiModel(description = "Фильтр \"Наличие реферера\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class ReferrerFilterDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("referrerSpecified")
  private Boolean referrerSpecified = null;

  public ReferrerFilterDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Имя фильтра.
   * @return name
  **/
  @ApiModelProperty(value = "Имя фильтра.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ReferrerFilterDto referrerSpecified(Boolean referrerSpecified) {
    this.referrerSpecified = referrerSpecified;
    return this;
  }

   /**
   * Есть реферер или нет.
   * @return referrerSpecified
  **/
  @ApiModelProperty(value = "Есть реферер или нет.")
  public Boolean isReferrerSpecified() {
    return referrerSpecified;
  }

  public void setReferrerSpecified(Boolean referrerSpecified) {
    this.referrerSpecified = referrerSpecified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferrerFilterDto referrerFilterDto = (ReferrerFilterDto) o;
    return Objects.equals(this.name, referrerFilterDto.name) &&
        Objects.equals(this.referrerSpecified, referrerFilterDto.referrerSpecified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, referrerSpecified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferrerFilterDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    referrerSpecified: ").append(toIndentedString(referrerSpecified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

