/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Модель для прикрепления телефона.
 */
@ApiModel(description = "Модель для прикрепления телефона.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class SetNewPhoneModel {
  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("withoutCall")
  private Boolean withoutCall = null;

  public SetNewPhoneModel phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Телефон.
   * @return phone
  **/
  @ApiModelProperty(value = "Телефон.")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public SetNewPhoneModel withoutCall(Boolean withoutCall) {
    this.withoutCall = withoutCall;
    return this;
  }

   /**
   * Прикрепление телефона без звонка.
   * @return withoutCall
  **/
  @ApiModelProperty(value = "Прикрепление телефона без звонка.")
  public Boolean isWithoutCall() {
    return withoutCall;
  }

  public void setWithoutCall(Boolean withoutCall) {
    this.withoutCall = withoutCall;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetNewPhoneModel setNewPhoneModel = (SetNewPhoneModel) o;
    return Objects.equals(this.phone, setNewPhoneModel.phone) &&
        Objects.equals(this.withoutCall, setNewPhoneModel.withoutCall);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, withoutCall);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetNewPhoneModel {\n");
    
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    withoutCall: ").append(toIndentedString(withoutCall)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

