/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View-model для фильтра \&quot;Активность в социальных сетях\&quot;.
 */
@ApiModel(description = "View-model для фильтра \"Активность в социальных сетях\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class SocialActivityFilterViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isDeletedFilterType")
  private Boolean isDeletedFilterType = null;

  /**
   * Провайдер (социальная сеть).
   */
  public enum ProviderTypeEnum {
    FACEBOOK("Facebook"),
    
    VKONTAKTE("VKontakte"),
    
    INSTAGRAM("Instagram"),
    
    TWITTER("Twitter"),
    
    GOOGLE("Google"),
    
    MYMAIL("MyMail"),
    
    ODNOKLASSNIKI("Odnoklassniki"),
    
    LOYMAX("Loymax");

    private String value;

    ProviderTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderTypeEnum fromValue(String text) {
      for (ProviderTypeEnum b : ProviderTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("providerType")
  private ProviderTypeEnum providerType = null;

  /**
   * Тип активности.
   */
  public enum ActivityTypeEnum {
    REACTION("Reaction"),
    
    COMMENT("Comment"),
    
    SHARE("Share");

    private String value;

    ActivityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActivityTypeEnum fromValue(String text) {
      for (ActivityTypeEnum b : ActivityTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("activityType")
  private ActivityTypeEnum activityType = null;

  @JsonProperty("objects")
  private String objects = null;

  public SocialActivityFilterViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SocialActivityFilterViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SocialActivityFilterViewModel isDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
    return this;
  }

   /**
   * Get isDeletedFilterType
   * @return isDeletedFilterType
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeletedFilterType() {
    return isDeletedFilterType;
  }

  public void setIsDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
  }

  public SocialActivityFilterViewModel providerType(ProviderTypeEnum providerType) {
    this.providerType = providerType;
    return this;
  }

   /**
   * Провайдер (социальная сеть).
   * @return providerType
  **/
  @ApiModelProperty(value = "Провайдер (социальная сеть).")
  public ProviderTypeEnum getProviderType() {
    return providerType;
  }

  public void setProviderType(ProviderTypeEnum providerType) {
    this.providerType = providerType;
  }

  public SocialActivityFilterViewModel activityType(ActivityTypeEnum activityType) {
    this.activityType = activityType;
    return this;
  }

   /**
   * Тип активности.
   * @return activityType
  **/
  @ApiModelProperty(value = "Тип активности.")
  public ActivityTypeEnum getActivityType() {
    return activityType;
  }

  public void setActivityType(ActivityTypeEnum activityType) {
    this.activityType = activityType;
  }

  public SocialActivityFilterViewModel objects(String objects) {
    this.objects = objects;
    return this;
  }

   /**
   * Отслеживаемые объекты.
   * @return objects
  **/
  @ApiModelProperty(value = "Отслеживаемые объекты.")
  public String getObjects() {
    return objects;
  }

  public void setObjects(String objects) {
    this.objects = objects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialActivityFilterViewModel socialActivityFilterViewModel = (SocialActivityFilterViewModel) o;
    return Objects.equals(this.id, socialActivityFilterViewModel.id) &&
        Objects.equals(this.name, socialActivityFilterViewModel.name) &&
        Objects.equals(this.isDeletedFilterType, socialActivityFilterViewModel.isDeletedFilterType) &&
        Objects.equals(this.providerType, socialActivityFilterViewModel.providerType) &&
        Objects.equals(this.activityType, socialActivityFilterViewModel.activityType) &&
        Objects.equals(this.objects, socialActivityFilterViewModel.objects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isDeletedFilterType, providerType, activityType, objects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialActivityFilterViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isDeletedFilterType: ").append(toIndentedString(isDeletedFilterType)).append("\n");
    sb.append("    providerType: ").append(toIndentedString(providerType)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("    objects: ").append(toIndentedString(objects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

