/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Строковое значение атрибута.
 */
@ApiModel(description = "Строковое значение атрибута.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class StringAttributeValue {
  @JsonProperty("value")
  private String value = null;

  @JsonProperty("attributeId")
  private Integer attributeId = null;

  @JsonProperty("attributeLogicalName")
  private String attributeLogicalName = null;

  @JsonProperty("attributeName")
  private String attributeName = null;

  @JsonProperty("isRelated")
  private Boolean isRelated = null;

  public StringAttributeValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Значение.
   * @return value
  **/
  @ApiModelProperty(value = "Значение.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public StringAttributeValue attributeId(Integer attributeId) {
    this.attributeId = attributeId;
    return this;
  }

   /**
   * Id атрибута.
   * @return attributeId
  **/
  @ApiModelProperty(value = "Id атрибута.")
  public Integer getAttributeId() {
    return attributeId;
  }

  public void setAttributeId(Integer attributeId) {
    this.attributeId = attributeId;
  }

  public StringAttributeValue attributeLogicalName(String attributeLogicalName) {
    this.attributeLogicalName = attributeLogicalName;
    return this;
  }

   /**
   * Логическое имя атрибута.
   * @return attributeLogicalName
  **/
  @ApiModelProperty(value = "Логическое имя атрибута.")
  public String getAttributeLogicalName() {
    return attributeLogicalName;
  }

  public void setAttributeLogicalName(String attributeLogicalName) {
    this.attributeLogicalName = attributeLogicalName;
  }

  public StringAttributeValue attributeName(String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Имя атрибута.
   * @return attributeName
  **/
  @ApiModelProperty(value = "Имя атрибута.")
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  public StringAttributeValue isRelated(Boolean isRelated) {
    this.isRelated = isRelated;
    return this;
  }

   /**
   * Значение атрибута получено из связанной сущности.
   * @return isRelated
  **/
  @ApiModelProperty(value = "Значение атрибута получено из связанной сущности.")
  public Boolean isIsRelated() {
    return isRelated;
  }

  public void setIsRelated(Boolean isRelated) {
    this.isRelated = isRelated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StringAttributeValue stringAttributeValue = (StringAttributeValue) o;
    return Objects.equals(this.value, stringAttributeValue.value) &&
        Objects.equals(this.attributeId, stringAttributeValue.attributeId) &&
        Objects.equals(this.attributeLogicalName, stringAttributeValue.attributeLogicalName) &&
        Objects.equals(this.attributeName, stringAttributeValue.attributeName) &&
        Objects.equals(this.isRelated, stringAttributeValue.isRelated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, attributeId, attributeLogicalName, attributeName, isRelated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StringAttributeValue {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    attributeId: ").append(toIndentedString(attributeId)).append("\n");
    sb.append("    attributeLogicalName: ").append(toIndentedString(attributeLogicalName)).append("\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    isRelated: ").append(toIndentedString(isRelated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

