/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Состояния метода оповещения.
 */
@ApiModel(description = "Состояния метода оповещения.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class SubscriptionNotificationStateModel {
  @JsonProperty("readOnly")
  private Boolean readOnly = null;

  @JsonProperty("selected")
  private Boolean selected = null;

  public SubscriptionNotificationStateModel readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Недоступен для изменения.
   * @return readOnly
  **/
  @ApiModelProperty(value = "Недоступен для изменения.")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public SubscriptionNotificationStateModel selected(Boolean selected) {
    this.selected = selected;
    return this;
  }

   /**
   * Клиент подписан.
   * @return selected
  **/
  @ApiModelProperty(value = "Клиент подписан.")
  public Boolean isSelected() {
    return selected;
  }

  public void setSelected(Boolean selected) {
    this.selected = selected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionNotificationStateModel subscriptionNotificationStateModel = (SubscriptionNotificationStateModel) o;
    return Objects.equals(this.readOnly, subscriptionNotificationStateModel.readOnly) &&
        Objects.equals(this.selected, subscriptionNotificationStateModel.selected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readOnly, selected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionNotificationStateModel {\n");
    
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

