/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View модель целевой аудитории.
 */
@ApiModel(description = "View модель целевой аудитории.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class TargetGroupBriefViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isArchived")
  private Boolean isArchived = null;

  public TargetGroupBriefViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Id целевой аудитории.
   * @return id
  **/
  @ApiModelProperty(value = "Id целевой аудитории.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TargetGroupBriefViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Имя.
   * @return name
  **/
  @ApiModelProperty(value = "Имя.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TargetGroupBriefViewModel isArchived(Boolean isArchived) {
    this.isArchived = isArchived;
    return this;
  }

   /**
   * Признак архивирования ЦА.
   * @return isArchived
  **/
  @ApiModelProperty(value = "Признак архивирования ЦА.")
  public Boolean isIsArchived() {
    return isArchived;
  }

  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetGroupBriefViewModel targetGroupBriefViewModel = (TargetGroupBriefViewModel) o;
    return Objects.equals(this.id, targetGroupBriefViewModel.id) &&
        Objects.equals(this.name, targetGroupBriefViewModel.name) &&
        Objects.equals(this.isArchived, targetGroupBriefViewModel.isArchived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isArchived);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetGroupBriefViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isArchived: ").append(toIndentedString(isArchived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

