/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * View модель фильтра \&quot;Целевые аудитории\&quot;.
 */
@ApiModel(description = "View модель фильтра \"Целевые аудитории\".")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class TargetGroupFilterViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isDeletedFilterType")
  private Boolean isDeletedFilterType = null;

  @JsonProperty("targetGroups")
  private List<TargetGroupBriefViewModel> targetGroups = null;

  public TargetGroupFilterViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TargetGroupFilterViewModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TargetGroupFilterViewModel isDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
    return this;
  }

   /**
   * Get isDeletedFilterType
   * @return isDeletedFilterType
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDeletedFilterType() {
    return isDeletedFilterType;
  }

  public void setIsDeletedFilterType(Boolean isDeletedFilterType) {
    this.isDeletedFilterType = isDeletedFilterType;
  }

  public TargetGroupFilterViewModel targetGroups(List<TargetGroupBriefViewModel> targetGroups) {
    this.targetGroups = targetGroups;
    return this;
  }

  public TargetGroupFilterViewModel addTargetGroupsItem(TargetGroupBriefViewModel targetGroupsItem) {
    if (this.targetGroups == null) {
      this.targetGroups = new ArrayList<>();
    }
    this.targetGroups.add(targetGroupsItem);
    return this;
  }

   /**
   * Список идентификаторов выбранных целевых аудиторий.
   * @return targetGroups
  **/
  @ApiModelProperty(value = "Список идентификаторов выбранных целевых аудиторий.")
  public List<TargetGroupBriefViewModel> getTargetGroups() {
    return targetGroups;
  }

  public void setTargetGroups(List<TargetGroupBriefViewModel> targetGroups) {
    this.targetGroups = targetGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetGroupFilterViewModel targetGroupFilterViewModel = (TargetGroupFilterViewModel) o;
    return Objects.equals(this.id, targetGroupFilterViewModel.id) &&
        Objects.equals(this.name, targetGroupFilterViewModel.name) &&
        Objects.equals(this.isDeletedFilterType, targetGroupFilterViewModel.isDeletedFilterType) &&
        Objects.equals(this.targetGroups, targetGroupFilterViewModel.targetGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isDeletedFilterType, targetGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetGroupFilterViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isDeletedFilterType: ").append(toIndentedString(isDeletedFilterType)).append("\n");
    sb.append("    targetGroups: ").append(toIndentedString(targetGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

