/*
 * Loymax.SystemApi
 * Loymax version: 2020.1.1.55071
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package restclient.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * View Model для TemplateSimple.
 */
@ApiModel(description = "View Model для TemplateSimple.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-25T13:30:11.810+03:00")
public class TemplateSimpleViewModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("logicalName")
  private String logicalName = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("priority")
  private Integer priority = null;

  /**
   * Тип подписки.
   */
  public enum SubscriptionTypeEnum {
    CASHBACK("Cashback"),
    
    PAYMENT("Payment"),
    
    REFILL("Refill"),
    
    OFFER("Offer"),
    
    SYSTEM("System"),
    
    MAILING("Mailing"),
    
    REFUND("Refund"),
    
    DEVICEEMULATION("DeviceEmulation");

    private String value;

    SubscriptionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SubscriptionTypeEnum fromValue(String text) {
      for (SubscriptionTypeEnum b : SubscriptionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("subscriptionType")
  private SubscriptionTypeEnum subscriptionType = null;

  @JsonProperty("isDeleted")
  private Boolean isDeleted = null;

  @JsonProperty("canNotBeDeleted")
  private Boolean canNotBeDeleted = null;

  public TemplateSimpleViewModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор.
   * @return id
  **/
  @ApiModelProperty(value = "Идентификатор.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TemplateSimpleViewModel logicalName(String logicalName) {
    this.logicalName = logicalName;
    return this;
  }

   /**
   * Уникальное логическое имя.
   * @return logicalName
  **/
  @ApiModelProperty(value = "Уникальное логическое имя.")
  public String getLogicalName() {
    return logicalName;
  }

  public void setLogicalName(String logicalName) {
    this.logicalName = logicalName;
  }

  public TemplateSimpleViewModel text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Текст.
   * @return text
  **/
  @ApiModelProperty(value = "Текст.")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public TemplateSimpleViewModel priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Приоритет.
   * @return priority
  **/
  @ApiModelProperty(value = "Приоритет.")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public TemplateSimpleViewModel subscriptionType(SubscriptionTypeEnum subscriptionType) {
    this.subscriptionType = subscriptionType;
    return this;
  }

   /**
   * Тип подписки.
   * @return subscriptionType
  **/
  @ApiModelProperty(value = "Тип подписки.")
  public SubscriptionTypeEnum getSubscriptionType() {
    return subscriptionType;
  }

  public void setSubscriptionType(SubscriptionTypeEnum subscriptionType) {
    this.subscriptionType = subscriptionType;
  }

  public TemplateSimpleViewModel isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Флаг удаления.
   * @return isDeleted
  **/
  @ApiModelProperty(value = "Флаг удаления.")
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public TemplateSimpleViewModel canNotBeDeleted(Boolean canNotBeDeleted) {
    this.canNotBeDeleted = canNotBeDeleted;
    return this;
  }

   /**
   * Может ли сущность быть удалена.
   * @return canNotBeDeleted
  **/
  @ApiModelProperty(value = "Может ли сущность быть удалена.")
  public Boolean isCanNotBeDeleted() {
    return canNotBeDeleted;
  }

  public void setCanNotBeDeleted(Boolean canNotBeDeleted) {
    this.canNotBeDeleted = canNotBeDeleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateSimpleViewModel templateSimpleViewModel = (TemplateSimpleViewModel) o;
    return Objects.equals(this.id, templateSimpleViewModel.id) &&
        Objects.equals(this.logicalName, templateSimpleViewModel.logicalName) &&
        Objects.equals(this.text, templateSimpleViewModel.text) &&
        Objects.equals(this.priority, templateSimpleViewModel.priority) &&
        Objects.equals(this.subscriptionType, templateSimpleViewModel.subscriptionType) &&
        Objects.equals(this.isDeleted, templateSimpleViewModel.isDeleted) &&
        Objects.equals(this.canNotBeDeleted, templateSimpleViewModel.canNotBeDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, logicalName, text, priority, subscriptionType, isDeleted, canNotBeDeleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateSimpleViewModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    logicalName: ").append(toIndentedString(logicalName)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    subscriptionType: ").append(toIndentedString(subscriptionType)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    canNotBeDeleted: ").append(toIndentedString(canNotBeDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

